name: 6156-capstone
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xgboost
  - opencv
  - fastapi
  - uvicorn
  - ipykernel
  - jupyterlab
  - pip:
      - mediapipe==0.10.9
      - ultralytics==8.0.196
      - protobuf>=3.20.3,<4
      - google-cloud-storage
      - python-dotenv
